# permissions for end users to edit managedserviceaccounts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: managedserviceaccount-editor-role
rules:
- apiGroups:
  - authentication.open-cluster-management.io.open-cluster-management.io
  resources:
  - managedserviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - authentication.open-cluster-management.io.open-cluster-management.io
  resources:
  - managedserviceaccounts/status
  verbs:
  - get
