# permissions for end users to view managedserviceaccounts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: managedserviceaccount-viewer-role
rules:
- apiGroups:
  - authentication.open-cluster-management.io.open-cluster-management.io
  resources:
  - managedserviceaccounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - authentication.open-cluster-management.io.open-cluster-management.io
  resources:
  - managedserviceaccounts/status
  verbs:
  - get
